/**
 * SDBC Data Types, defined in C
 *
 * Defined per device
 *
 * Initial file is autogenerated if non existant
 * Data types should be filled out by user
 */

#include <stdint.h>

#define SDBC_TYPE_DEFINITIONS \
    X(long_t, int64_t)        \
    X(int_t, int32_t)         \
    X(short_t, int16_t)       \
    X(byte_t, int8_t)         \
    X(ulong_t, uint64_t)      \
    X(uint_t, uint32_t)       \
    X(ushort_t, uint16_t)     \
    X(ubyte_t, uint8_t)       \
    X(float_t, float)         \
    X(double_t, double)       \
    X(bool_t, bool)           \
    X(binary_t, uint32_t)

namespace SDBC {

enum dt {
#define X(dt_id, typ) dt_id,
    SDBC_TYPE_DEFINITIONS
#undef X
};

} // namespace SDBC