/**
 * SDBC Data Types, defined in C
 *
 * Defined per device
 *
 * Inital file is autogenerated if non existant
 */

#include <stdint.h>

using sdbc_long_t = int64_t;
using sdbc_int_t = int32_t;
using sdbc_short_t = int16_t;
using sdbc_byte_t = int8_t;
using sdbc_ulong_t = uint64_t;
using sdbc_uint_t = uint32_t;
using sdbc_ushort_t = uint16_t;
using sdbc_ubyte_t = uint8_t;
using sdbc_float_t = float;
using sdbc_double_t = double;
using sdbc_bool_t = bool;
using sdbc_binary_t = uint32_t;